import { useEffect, useMemo, useState } from 'react'
import { useNavigate } from 'react-router-dom'
import { AlertTriangle, CalendarDays, History, LogOut, Plus, Radio, Users, X } from 'lucide-react'
import { createPlannedSession, subscribeTeacherWorkspace } from '../services/pilotRepository'
import { useAuth } from '../context/AuthContext'
import { signOutUser } from '../services/authService'

const statusMeta={planned:{label:'Gepland',icon:CalendarDays,accent:'text-indigo-600',empty:'Nog geen geplande sessies.'},live:{label:'Live',icon:Radio,accent:'text-emerald-600',empty:'Geen actieve sessie.'},ended:{label:'Historie',icon:History,accent:'text-slate-500',empty:'Nog geen sessiehistorie.'}}
function prettyDate(s){return new Intl.DateTimeFormat('nl-NL',{weekday:'short',day:'numeric',month:'long',hour:'2-digit',minute:'2-digit'}).format(new Date(`${s.scheduledDate}T${s.scheduledStartTime||'12:00'}`))}
export default function TeacherWorkspace(){
 const navigate=useNavigate(),{profile}=useAuth()
 const [data,setData]=useState(null),[error,setError]=useState(''),[groupId,setGroupId]=useState(''),[planning,setPlanning]=useState(false)
 useEffect(()=>subscribeTeacherWorkspace(r=>{setError('');setData(r)},p=>setError(p.message)),[])
 const groups=useMemo(()=>{if(!data)return[];const active=data.groups.filter(g=>g.active!==false);return profile?.role==='teacher'?active.filter(g=>profile.groupIds?.includes(g.id)):active},[data,profile])
 useEffect(()=>{if(!groups.length){setGroupId('');return}if(!groups.some(g=>g.id===groupId))setGroupId(groups[0].id)},[groups,groupId])
 const group=groups.find(g=>g.id===groupId),sessions=useMemo(()=>(data?.sessions||[]).filter(s=>s.groupId===groupId),[data,groupId])
 if(error)return <BackendGate message={error}/>
 if(!data)return <div className="min-h-screen grid place-items-center text-indigo-600">Gedeelde schoolomgeving laden…</div>
 return <main className="min-h-screen bg-gradient-to-br from-indigo-50 via-white to-emerald-50 text-gray-900">
  <header className="border-b border-white/70 bg-white/70 backdrop-blur"><div className="mx-auto flex max-w-6xl flex-col gap-5 px-5 py-6 md:flex-row md:items-center md:justify-between">
   <div><p className="text-sm font-semibold text-indigo-600">{data.school?.name||'Live Vertaal Service'} · Pilot V3</p><h1 className="mt-1 text-3xl font-bold">Welkom terug, {profile?.displayName||'collega'}! 👋</h1><p className="mt-1 text-gray-600">Plan oudercontacten vooraf en beheer ze samen met je collega's.</p></div>
   <div className="flex flex-wrap gap-2"><button onClick={()=>signOutUser()} className="inline-flex items-center gap-2 rounded-xl border border-gray-200 bg-white px-4 py-3 font-semibold text-gray-600"><LogOut className="h-4 w-4"/>Uitloggen</button><button onClick={()=>setPlanning(true)} disabled={!groups.length} className="inline-flex items-center gap-2 rounded-xl bg-gradient-to-r from-indigo-500 to-sky-500 px-5 py-3 font-semibold text-white shadow-lg disabled:opacity-50"><Plus className="h-5 w-5"/>Sessie plannen</button></div>
  </div></header>
  <section className="mx-auto max-w-6xl px-5 py-8">
   <div className="mb-7 flex flex-wrap gap-3">{groups.map(g=><button key={g.id} onClick={()=>setGroupId(g.id)} className={`rounded-xl border px-4 py-2.5 font-semibold ${g.id===groupId?'border-indigo-200 bg-indigo-600 text-white shadow-md':'border-white bg-white/80 text-gray-700'}`}>{g.name}</button>)}</div>
   {!groups.length?<div className="rounded-3xl border border-indigo-100 bg-white p-8 shadow-sm"><h2 className="text-xl font-bold">Nog geen groepen toegewezen</h2><p className="mt-2 text-gray-600">{profile?.role==='teacher'?'Een schooladmin kan je vanuit het beheerportaal aan één of meer groepen koppelen.':'Maak eerst een groep aan in het platformbeheer.'}</p></div>:
   <div className="glass-effect rounded-3xl border border-white/80 p-6 shadow-xl"><div className="flex flex-col gap-3 border-b border-gray-100 pb-5 sm:flex-row sm:items-end sm:justify-between"><div><p className="text-sm font-medium text-gray-500">Gezamenlijke groepsomgeving</p><h2 className="text-2xl font-bold">{group?.name}</h2></div><div className="flex items-center gap-2 text-sm text-gray-600"><Users className="h-4 w-4"/><span>Jouw rol: {profile?.role==='platformAdmin'?'Platformbeheerder':profile?.role==='schoolAdmin'?'Schoolbeheerder':'Leerkracht'}</span></div></div>
    <div className="mt-6 grid gap-5 lg:grid-cols-3">{Object.entries(statusMeta).map(([status,m])=>{const Icon=m.icon,items=sessions.filter(s=>s.status===status);return <section key={status} className="rounded-2xl border border-gray-100 bg-white/80 p-4"><div className="flex items-center gap-2"><Icon className={`h-5 w-5 ${m.accent}`}/><h3 className="font-bold">{m.label}</h3><span className="ml-auto rounded-full bg-gray-100 px-2 py-0.5 text-xs font-semibold">{items.length}</span></div><div className="mt-4 space-y-3">{!items.length&&<p className="py-5 text-sm text-gray-400">{m.empty}</p>}{items.map(s=><button key={s.id} onClick={()=>navigate(`/teacher/session/${s.id}`)} className="w-full rounded-xl border border-gray-100 bg-white p-4 text-left shadow-sm hover:border-indigo-200"><p className="font-bold">{s.title}</p><p className="mt-2 text-sm text-gray-500">{prettyDate(s)}</p>{status==='ended'&&<p className="mt-2 text-xs font-medium text-indigo-600">{s.participantCount||0} deelnames · Transcript beschikbaar</p>}</button>)}</div></section>})}</div>
   </div>}
  </section>
  {planning&&<Planner groups={groups} initialGroupId={groupId} onClose={()=>setPlanning(false)} onCreated={s=>{setPlanning(false);navigate(`/teacher/session/${s.id}`)}}/>}
 </main>
}
function BackendGate({message}){return <main className="min-h-screen grid place-items-center p-5"><div className="max-w-xl rounded-3xl bg-white p-7 shadow-xl"><div className="flex gap-3"><AlertTriangle className="text-amber-500"/><h1 className="text-xl font-bold">Geen toegang tot de schoolomgeving</h1></div><p className="mt-3 text-gray-600">{message}</p></div></main>}
function Planner({groups,initialGroupId,onClose,onCreated}){
 const [form,setForm]=useState({groupId:initialGroupId,title:'',scheduledDate:'',scheduledStartTime:'19:00',summaryEnabled:true}),[saving,setSaving]=useState(false),[error,setError]=useState('')
 const change=k=>e=>setForm(c=>({...c,[k]:e.target.type==='checkbox'?e.target.checked:e.target.value}))
 async function submit(e){e.preventDefault();setSaving(true);setError('');try{onCreated(await createPlannedSession(form))}catch(p){setError(p.message||'Opslaan mislukt.')}finally{setSaving(false)}}
 return <div className="fixed inset-0 z-50 grid place-items-center bg-slate-900/30 p-4 backdrop-blur-sm"><form onSubmit={submit} className="w-full max-w-lg rounded-3xl bg-white p-6 shadow-2xl"><div className="flex justify-between"><div><p className="text-sm font-semibold text-indigo-600">Rustig vooraf klaarzetten</p><h2 className="text-2xl font-bold">Sessie plannen</h2></div><button type="button" onClick={onClose}><X/></button></div><div className="mt-6 space-y-4"><label className="block text-sm font-semibold">Groep<select required value={form.groupId} onChange={change('groupId')} className="mt-1.5 w-full rounded-xl border p-3 font-normal">{groups.map(g=><option key={g.id} value={g.id}>{g.name}</option>)}</select></label><label className="block text-sm font-semibold">Naam van het gesprek<input required value={form.title} onChange={change('title')} className="mt-1.5 w-full rounded-xl border p-3 font-normal"/></label><div className="grid grid-cols-2 gap-3"><input required type="date" value={form.scheduledDate} onChange={change('scheduledDate')} className="rounded-xl border p-3"/><input required type="time" value={form.scheduledStartTime} onChange={change('scheduledStartTime')} className="rounded-xl border p-3"/></div><label className="flex gap-3 rounded-xl bg-indigo-50 p-4"><input type="checkbox" checked={form.summaryEnabled} onChange={change('summaryEnabled')}/><span className="text-sm"><strong className="block">Samenvatting voor ouders</strong>Pas na controle en goedkeuring beschikbaar.</span></label>{error&&<p className="text-amber-700">{error}</p>}</div><div className="mt-6 flex justify-end gap-3"><button type="button" onClick={onClose}>Annuleren</button><button disabled={saving} className="rounded-xl bg-indigo-600 px-5 py-3 font-semibold text-white">{saving?'Opslaan…':'Sessie plannen'}</button></div></form></div>
}
